# install mariadb on mac
# $ brew install mariadb 
# $ mysql.server start|stop
# init root password at first start: 
# sql> ALTER USER 'root'@'localhost' IDENTIFIED BY 'mypassword';
# sql> flush privileges;
user = "root"
password = "nqq123"
# host = "172.31.74.249"
# port = 3306
name="mysql"
network = "tcp"
dbname = "real_world_medium"
timeout = "10s"
